image: mtmiller/octave:devel

before_script:
  - apt-get update -qq && apt-get install -y -qq shunit2
  - octave --version
  - octave --eval="ver Octave"

test:
  script:
    - sh octave-shunit-test.sh
