image: mtmiller/octave

before_script:
  - apt-get update -qq && apt-get install -y -qq shunit2
  - octave --version
  - octave --eval="ver Octave"

stages:
  - test

test stable:
  stage: test
  script:
    - sh octave-shunit-test.sh

test devel:
  image: mtmiller/octave:devel
  extends: test stable
