---
services:
  - docker

before_install:
  - export TAG='octave-test-suite:travis'
  - docker build -t ${TAG} travis
  - docker run -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v ${PWD}:/test:ro ${TAG} > /tmp/container
  - export CONTAINER=$(cat /tmp/container)

script:
  - docker exec ${CONTAINER} octave --version
  - docker exec ${CONTAINER} octave --eval "ver Octave"
  - docker exec ${CONTAINER} /test/octave-shunit-test.sh
